apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: {{ .Values.allowHttp | default "false" | quote }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  name: {{ printf "%s-%s" $.Release.Name "bookstack" }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.appHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
              name: {{ printf "%s-%s" $.Release.Name "bookstack" }}
              port:
                number: 8080
        
  tls:
  - hosts:
    - {{ .Values.appHost }}
    secretName: {{ printf "%s-%s" $.Release.Name "bookstack" }}