apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  name: {{ printf "%s-%s" $.Release.Name "bookstack" }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ $.Values.appHost }}
    http:
      paths:
      - backend:
          serviceName: {{ printf "%s-%s" $.Release.Name "bookstack" }}
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - {{ $.Values.appHost }}
    secretName: {{ printf "%s-%s" $.Release.Name "bookstack" }}