apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ printf "%s-%s" .Release.Name "mysql" }}
  name: {{ printf "%s-%s" .Release.Name "mysql" }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: {{ printf "%s-%s" .Release.Name "mysql" }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Release.Name "mysql" }}
    spec:
      initContainers:
      - image: busybox
        name: bookstack-mysql-init
        command: 
          - sh
          - "-c"
          - "rm -rf /mnt/lost+found"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /mnt/
          name: bookstack-mysql
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: bookstack
        - name: MYSQL_USER
          value: bookstack
        - name: MYSQL_PASSWORD
          value: secret
        image: mysql:5.7
        name: bookstack-mysql
        args: ["--max_allowed_packet=24M"]
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: bookstack-mysql
      volumes:
      - name: bookstack-mysql
        persistentVolumeClaim:
          claimName: {{ printf "%s-%s" .Release.Name "mysql" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ printf "%s-%s" .Release.Name "mysql" }}
  name: {{ printf "%s-%s" .Release.Name "mysql" }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: {{ printf "%s-%s" .Release.Name "mysql" }}
  type: ClusterIP