name: Check Markdown Links

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Check Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/mdlink/mlc_config.json"
