name: Test and Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Chart
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
      - id: list-changed
        name: List Changed
        run: |
          changed="$(ct list-changed)"
          if [ -n "$changed" ]; then
            echo "::set-output name=changed::true"
          fi
      - name: Lint
        run: ct lint
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'
      - name: Install
        run: ct install

