name: Test and Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Chart
    runs-on: ubuntu-20.04
    env:
      CT_TARGET_BRANCH: main
      CT_CHART_DIRS: ${{ github.workspace }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
      - id: list-changed
        name: List Changed
        run: |
          changed=$(ct list-changed)
          if [[ -z "$changed" ]]; then
            echo "::error::No chart changes detected"
            exit 99
          fi
      - name: Lint
        run: ct lint
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
      - name: Install
        run: ct install
  publish:
    name: Publish Chart
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.3
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_OWNER: pacroy
          CR_GIT_REPO: helm
          CR_TOKEN: "${{ secrets.HELM_REPO_TOKEN }}"
        with:
          charts_dir: ${{ github.workspace }}

